package com.urja.model;
// Generated Jul 19, 2016 11:26:33 PM by Hibernate Tools 4.3.1.Final

/**
 * Backofficeuser generated by hbm2java
 */
public class Backofficeuser implements java.io.Serializable {

	private BackofficeuserId id;

	public Backofficeuser() {
	}

	public Backofficeuser(BackofficeuserId id) {
		this.id = id;
	}

	public BackofficeuserId getId() {
		return this.id;
	}

	public void setId(BackofficeuserId id) {
		this.id = id;
	}

}
