package com.urja.model;
// Generated Jul 19, 2016 11:26:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private Integer bookingid;
	private Address address;
	private Customer customer;
	private Paymentdetail paymentdetail;
	private Date bookingdatetime;
	private Date pickuptime1;
	private Date pickuptime2;
	private Date delivertime1;
	private Date delivertime2;
	private String status;
	private Date stampdate;
	private String stampuser;
	private Set bookingitemses = new HashSet(0);

	public Booking() {
	}

	public Booking(Date bookingdatetime, Date pickuptime1, Date pickuptime2, Date delivertime1, Date delivertime2,
			String status, Date stampdate, String stampuser) {
		this.bookingdatetime = bookingdatetime;
		this.pickuptime1 = pickuptime1;
		this.pickuptime2 = pickuptime2;
		this.delivertime1 = delivertime1;
		this.delivertime2 = delivertime2;
		this.status = status;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Booking(Address address, Customer customer, Paymentdetail paymentdetail, Date bookingdatetime,
			Date pickuptime1, Date pickuptime2, Date delivertime1, Date delivertime2, String status, Date stampdate,
			String stampuser, Set bookingitemses) {
		this.address = address;
		this.customer = customer;
		this.paymentdetail = paymentdetail;
		this.bookingdatetime = bookingdatetime;
		this.pickuptime1 = pickuptime1;
		this.pickuptime2 = pickuptime2;
		this.delivertime1 = delivertime1;
		this.delivertime2 = delivertime2;
		this.status = status;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
		this.bookingitemses = bookingitemses;
	}

	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Paymentdetail getPaymentdetail() {
		return this.paymentdetail;
	}

	public void setPaymentdetail(Paymentdetail paymentdetail) {
		this.paymentdetail = paymentdetail;
	}

	public Date getBookingdatetime() {
		return this.bookingdatetime;
	}

	public void setBookingdatetime(Date bookingdatetime) {
		this.bookingdatetime = bookingdatetime;
	}

	public Date getPickuptime1() {
		return this.pickuptime1;
	}

	public void setPickuptime1(Date pickuptime1) {
		this.pickuptime1 = pickuptime1;
	}

	public Date getPickuptime2() {
		return this.pickuptime2;
	}

	public void setPickuptime2(Date pickuptime2) {
		this.pickuptime2 = pickuptime2;
	}

	public Date getDelivertime1() {
		return this.delivertime1;
	}

	public void setDelivertime1(Date delivertime1) {
		this.delivertime1 = delivertime1;
	}

	public Date getDelivertime2() {
		return this.delivertime2;
	}

	public void setDelivertime2(Date delivertime2) {
		this.delivertime2 = delivertime2;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public Set getBookingitemses() {
		return this.bookingitemses;
	}

	public void setBookingitemses(Set bookingitemses) {
		this.bookingitemses = bookingitemses;
	}

}
