package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer customerid;
	private String firstname;
	private String middlename;
	private String lastname;
	private String email;
	private Long phone1;
	private Long phone2;
	private Date stampdate;
	private String stampuser;
	private Set addresses = new HashSet(0);
	private Set signups = new HashSet(0);

	public Customer() {
	}

	public Customer(String firstname, String middlename, String lastname, String email, Long phone1, Long phone2,
			Date stampdate, String stampuser) {
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.email = email;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Customer(String firstname, String middlename, String lastname, String email, Long phone1, Long phone2,
			Date stampdate, String stampuser, Set addresses, Set signups) {
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.email = email;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
		this.addresses = addresses;
		this.signups = signups;
	}

	public Integer getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getPhone1() {
		return this.phone1;
	}

	public void setPhone1(Long phone1) {
		this.phone1 = phone1;
	}

	public Long getPhone2() {
		return this.phone2;
	}

	public void setPhone2(Long phone2) {
		this.phone2 = phone2;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

	public Set getSignups() {
		return this.signups;
	}

	public void setSignups(Set signups) {
		this.signups = signups;
	}

}
