package com.urja.model;
// Generated Jul 19, 2016 11:26:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable {

	private Integer itemid;
	private String itemname;
	private Date stampdate;
	private String stampuser;
	private Set serviceitemses = new HashSet(0);

	public Items() {
	}

	public Items(String itemname, Date stampdate, String stampuser) {
		this.itemname = itemname;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Items(String itemname, Date stampdate, String stampuser, Set serviceitemses) {
		this.itemname = itemname;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
		this.serviceitemses = serviceitemses;
	}

	public Integer getItemid() {
		return this.itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public Set getServiceitemses() {
		return this.serviceitemses;
	}

	public void setServiceitemses(Set serviceitemses) {
		this.serviceitemses = serviceitemses;
	}

}
