package com.urja.model;
// Generated Jul 19, 2016 11:26:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paymentdetail generated by hbm2java
 */
public class Paymentdetail implements java.io.Serializable {

	private int orderid;
	private double billedamount;
	private double paidamount;
	private String paymenttype;
	private boolean paidinfullflag;
	private Date stampdate;
	private String stampuser;
	private Set bookings = new HashSet(0);

	public Paymentdetail() {
	}

	public Paymentdetail(int orderid, double billedamount, double paidamount, String paymenttype,
			boolean paidinfullflag, Date stampdate, String stampuser) {
		this.orderid = orderid;
		this.billedamount = billedamount;
		this.paidamount = paidamount;
		this.paymenttype = paymenttype;
		this.paidinfullflag = paidinfullflag;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Paymentdetail(int orderid, double billedamount, double paidamount, String paymenttype,
			boolean paidinfullflag, Date stampdate, String stampuser, Set bookings) {
		this.orderid = orderid;
		this.billedamount = billedamount;
		this.paidamount = paidamount;
		this.paymenttype = paymenttype;
		this.paidinfullflag = paidinfullflag;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
		this.bookings = bookings;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public double getBilledamount() {
		return this.billedamount;
	}

	public void setBilledamount(double billedamount) {
		this.billedamount = billedamount;
	}

	public double getPaidamount() {
		return this.paidamount;
	}

	public void setPaidamount(double paidamount) {
		this.paidamount = paidamount;
	}

	public String getPaymenttype() {
		return this.paymenttype;
	}

	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	public boolean isPaidinfullflag() {
		return this.paidinfullflag;
	}

	public void setPaidinfullflag(boolean paidinfullflag) {
		this.paidinfullflag = paidinfullflag;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

}
