package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PaymentdetailId generated by hbm2java
 */
public class PaymentdetailId implements java.io.Serializable {

	private int orderid;
	private int billedamount;
	private int paidamount;
	private String paymenttype;
	private boolean paidinfullflag;
	private Date stampdate;
	private String stampuser;

	public PaymentdetailId() {
	}

	public PaymentdetailId(int orderid, int billedamount, int paidamount, String paymenttype, boolean paidinfullflag,
			Date stampdate, String stampuser) {
		this.orderid = orderid;
		this.billedamount = billedamount;
		this.paidamount = paidamount;
		this.paymenttype = paymenttype;
		this.paidinfullflag = paidinfullflag;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public int getBilledamount() {
		return this.billedamount;
	}

	public void setBilledamount(int billedamount) {
		this.billedamount = billedamount;
	}

	public int getPaidamount() {
		return this.paidamount;
	}

	public void setPaidamount(int paidamount) {
		this.paidamount = paidamount;
	}

	public String getPaymenttype() {
		return this.paymenttype;
	}

	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	public boolean isPaidinfullflag() {
		return this.paidinfullflag;
	}

	public void setPaidinfullflag(boolean paidinfullflag) {
		this.paidinfullflag = paidinfullflag;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentdetailId))
			return false;
		PaymentdetailId castOther = (PaymentdetailId) other;

		return (this.getOrderid() == castOther.getOrderid()) && (this.getBilledamount() == castOther.getBilledamount())
				&& (this.getPaidamount() == castOther.getPaidamount())
				&& ((this.getPaymenttype() == castOther.getPaymenttype())
						|| (this.getPaymenttype() != null && castOther.getPaymenttype() != null
								&& this.getPaymenttype().equals(castOther.getPaymenttype())))
				&& (this.isPaidinfullflag() == castOther.isPaidinfullflag())
				&& ((this.getStampdate() == castOther.getStampdate()) || (this.getStampdate() != null
						&& castOther.getStampdate() != null && this.getStampdate().equals(castOther.getStampdate())))
				&& ((this.getStampuser() == castOther.getStampuser()) || (this.getStampuser() != null
						&& castOther.getStampuser() != null && this.getStampuser().equals(castOther.getStampuser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderid();
		result = 37 * result + this.getBilledamount();
		result = 37 * result + this.getPaidamount();
		result = 37 * result + (getPaymenttype() == null ? 0 : this.getPaymenttype().hashCode());
		result = 37 * result + (this.isPaidinfullflag() ? 1 : 0);
		result = 37 * result + (getStampdate() == null ? 0 : this.getStampdate().hashCode());
		result = 37 * result + (getStampuser() == null ? 0 : this.getStampuser().hashCode());
		return result;
	}

}
