package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

/**
 * Paymentdetail generated by hbm2java
 */
public class Paymentdetail implements java.io.Serializable {

	private PaymentdetailId id;

	public Paymentdetail() {
	}

	public Paymentdetail(PaymentdetailId id) {
		this.id = id;
	}

	public PaymentdetailId getId() {
		return this.id;
	}

	public void setId(PaymentdetailId id) {
		this.id = id;
	}

}
