package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

/**
 * Servicegroup generated by hbm2java
 */
public class Servicegroup implements java.io.Serializable {

	private ServicegroupId id;

	public Servicegroup() {
	}

	public Servicegroup(ServicegroupId id) {
		this.id = id;
	}

	public ServicegroupId getId() {
		return this.id;
	}

	public void setId(ServicegroupId id) {
		this.id = id;
	}

}
