package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ServicegroupId generated by hbm2java
 */
public class ServicegroupId implements java.io.Serializable {

	private int servicegroupcode;
	private String servicegrouptype;
	private String servicegroupdesc;
	private Date stampdate;
	private String stampuser;

	public ServicegroupId() {
	}

	public ServicegroupId(int servicegroupcode, String servicegrouptype, String servicegroupdesc, Date stampdate,
			String stampuser) {
		this.servicegroupcode = servicegroupcode;
		this.servicegrouptype = servicegrouptype;
		this.servicegroupdesc = servicegroupdesc;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public int getServicegroupcode() {
		return this.servicegroupcode;
	}

	public void setServicegroupcode(int servicegroupcode) {
		this.servicegroupcode = servicegroupcode;
	}

	public String getServicegrouptype() {
		return this.servicegrouptype;
	}

	public void setServicegrouptype(String servicegrouptype) {
		this.servicegrouptype = servicegrouptype;
	}

	public String getServicegroupdesc() {
		return this.servicegroupdesc;
	}

	public void setServicegroupdesc(String servicegroupdesc) {
		this.servicegroupdesc = servicegroupdesc;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicegroupId))
			return false;
		ServicegroupId castOther = (ServicegroupId) other;

		return (this.getServicegroupcode() == castOther.getServicegroupcode())
				&& ((this.getServicegrouptype() == castOther.getServicegrouptype())
						|| (this.getServicegrouptype() != null && castOther.getServicegrouptype() != null
								&& this.getServicegrouptype().equals(castOther.getServicegrouptype())))
				&& ((this.getServicegroupdesc() == castOther.getServicegroupdesc())
						|| (this.getServicegroupdesc() != null && castOther.getServicegroupdesc() != null
								&& this.getServicegroupdesc().equals(castOther.getServicegroupdesc())))
				&& ((this.getStampdate() == castOther.getStampdate()) || (this.getStampdate() != null
						&& castOther.getStampdate() != null && this.getStampdate().equals(castOther.getStampdate())))
				&& ((this.getStampuser() == castOther.getStampuser()) || (this.getStampuser() != null
						&& castOther.getStampuser() != null && this.getStampuser().equals(castOther.getStampuser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getServicegroupcode();
		result = 37 * result + (getServicegrouptype() == null ? 0 : this.getServicegrouptype().hashCode());
		result = 37 * result + (getServicegroupdesc() == null ? 0 : this.getServicegroupdesc().hashCode());
		result = 37 * result + (getStampdate() == null ? 0 : this.getStampdate().hashCode());
		result = 37 * result + (getStampuser() == null ? 0 : this.getStampuser().hashCode());
		return result;
	}

}
