package com.urja.model;
// Generated Jul 9, 2016 1:51:15 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

	private Integer serviceid;
	private int servicegroupcode;
	private String servicename;
	private int servicecode;
	private String servicedesc;
	private int chargesperkg;
	private Integer discount;
	private Date stampdate;
	private String stampuser;

	public Services() {
	}

	public Services(int servicegroupcode, String servicename, int servicecode, String servicedesc, int chargesperkg,
			Date stampdate, String stampuser) {
		this.servicegroupcode = servicegroupcode;
		this.servicename = servicename;
		this.servicecode = servicecode;
		this.servicedesc = servicedesc;
		this.chargesperkg = chargesperkg;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Services(int servicegroupcode, String servicename, int servicecode, String servicedesc, int chargesperkg,
			Integer discount, Date stampdate, String stampuser) {
		this.servicegroupcode = servicegroupcode;
		this.servicename = servicename;
		this.servicecode = servicecode;
		this.servicedesc = servicedesc;
		this.chargesperkg = chargesperkg;
		this.discount = discount;
		this.stampdate = stampdate;
		this.stampuser = stampuser;
	}

	public Integer getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	public int getServicegroupcode() {
		return this.servicegroupcode;
	}

	public void setServicegroupcode(int servicegroupcode) {
		this.servicegroupcode = servicegroupcode;
	}

	public String getServicename() {
		return this.servicename;
	}

	public void setServicename(String servicename) {
		this.servicename = servicename;
	}

	public int getServicecode() {
		return this.servicecode;
	}

	public void setServicecode(int servicecode) {
		this.servicecode = servicecode;
	}

	public String getServicedesc() {
		return this.servicedesc;
	}

	public void setServicedesc(String servicedesc) {
		this.servicedesc = servicedesc;
	}

	public int getChargesperkg() {
		return this.chargesperkg;
	}

	public void setChargesperkg(int chargesperkg) {
		this.chargesperkg = chargesperkg;
	}

	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

}
